name: fullstackphp

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php

  php:
    build: ./
    container_name: php
    expose:
      - 9000
    volumes:
      - ./:/usr/share/nginx/html
